### ISSUE TITLE
Signup component development

### ISSUE THREAD

**Issue by ayushkumar1610** [team-carpool/frontend#10]
### Develop a signup component.

Create a signup component where users will register themself. Implementation of the signup form will be done on the basis of the below **Model**.

![User Model](https://user-images.githubusercontent.com/60136299/197327538-612f4b94-a0de-4f30-a974-0c0dfd60174a.png)

Currently don't apply any custom CSS or advanced UI, that'll be done in another phase.
Just create a signup form with a basic UI and send User registration data in JSON as RequestBody to the backend.
The user registration form will ask users for their Email, Name, and Password.

The [backend's endpoint](https://github.com/team-carpool/backend/issues/4) URL will be shared in the comment soon.

Further Actions:

1. Start the development on the branch ```feature/signup```
2. Then test it locally
3. Then raise PR for it to merge in ```develop```

**Comment by ayushkumar1610** [comment]
Backend User Registration's Endpoint URL:
``` 127.0.0.1:8080/users/signup ```

**Comment by shubham0809200** [comment]
I have created the ui !!
![image](https://user-images.githubusercontent.com/61448739/196999711-1b412883-e416-4e61-9657-81f669be15e3.png)

**Comment by shubham0809200** [comment]
![image](https://user-images.githubusercontent.com/61448739/197022228-006d66d9-9bff-4103-85a8-e709504f8e16.png)

**Comment by ayushkumar1610** [comment]
After adding protocol i.e., http:// while requesting to API, concatenation of urls got fixed

**Comment by ayushkumar1610** [comment]
#12 
@shubham0809200 Thanks for your contribution.
Closing this.
