### ISSUE TITLE
Home page UI development

### ISSUE THREAD

**Issue by ayushkumar1610** [team-carpool/frontend#8]
Current UI of Home Page

![Current UI](https://user-images.githubusercontent.com/60136299/196663922-dfd9de12-ecbd-4d95-bd46-35253f89eeaf.png)

Need to develop a new UI in a way that should not be similar to google map but should be as convenient as that, and alignment will be such that the form will be on the left 30% of the screen and in the rest of the screen(70%) map will be there.

Below are two [references](https://candidate-test-08.web.app/):

![image](https://user-images.githubusercontent.com/60136299/196972661-9e5726ac-1f44-40be-a182-60049edf9e4d.png)

![image](https://user-images.githubusercontent.com/60136299/196666542-06463320-a4e7-4350-8c75-c2b43a3802c3.png)

Further Actions:
1. Start the development on the branch ```feature/home```
2. Then test it locally
3. Then raise PR for it to merge in ```develop```

**Comment by ayushkumar1610** [comment]
There will be majorly CSS modification, So assigning it to @vaibhav975

**Comment by vaibhav975** [comment]
#16
